"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Dna, ArrowLeft, Printer, Shield } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getResults, type FullResults } from "@/lib/api";

export default function DoctorNotePage() {
  const params = useParams();
  const caseId = params.id as string;
  const [results, setResults] = useState<FullResults | null>(null);

  useEffect(() => {
    getResults(caseId).then(setResults).catch(console.error);
  }, [caseId]);

  const doctorNote = results?.summaries?.find(
    (s) => s.summary_type === "doctor_note"
  );

  return (
    <div className="min-h-screen bg-white">
      {/* Print-hidden nav */}
      <nav className="border-b no-print">
        <div className="max-w-4xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link
              href={`/cases/${caseId}/results`}
              className="flex items-center gap-2 text-muted-foreground hover:text-foreground"
            >
              <ArrowLeft className="w-4 h-4" /> Results
            </Link>
            <div className="flex items-center gap-2">
              <Dna className="w-5 h-5 text-primary" />
              <span className="font-semibold">RxGenome</span>
            </div>
          </div>
          <Button size="sm" onClick={() => window.print()} className="gap-2">
            <Printer className="w-4 h-4" />
            Print / Export PDF
          </Button>
        </div>
      </nav>

      {/* Printable content */}
      <main className="max-w-3xl mx-auto px-8 py-12">
        {/* Print header */}
        <div className="text-center mb-8 border-b pb-6">
          <div className="flex items-center justify-center gap-2 mb-2">
            <Dna className="w-6 h-6 text-primary" />
            <h1 className="text-2xl font-bold">RxGenome</h1>
          </div>
          <p className="text-sm text-muted-foreground">
            Precision Medicine Discussion Note
          </p>
          <p className="text-xs text-muted-foreground mt-1">
            Case: {results?.case?.name || caseId} — Generated{" "}
            {new Date().toLocaleDateString("en-US", {
              year: "numeric",
              month: "long",
              day: "numeric",
            })}
          </p>
        </div>

        {/* Doctor note content */}
        {doctorNote ? (
          <div className="prose prose-sm max-w-none leading-relaxed whitespace-pre-wrap">
            {doctorNote.content}
          </div>
        ) : (
          <p className="text-muted-foreground text-center py-8">
            No doctor note available. Please run analysis first.
          </p>
        )}

        {/* Footer disclaimer */}
        <div className="mt-12 pt-6 border-t">
          <div className="flex items-start gap-2 text-xs text-muted-foreground">
            <Shield className="w-4 h-4 shrink-0 mt-0.5" />
            <p>
              <strong>Disclaimer:</strong> This document is generated by
              RxGenome, an educational precision-medicine interpretation
              assistant. It is not a clinical diagnostic report. All findings are
              derived from machine learning analysis and should be interpreted in
              the context of complete clinical evaluation. Consult a qualified
              healthcare provider before making any medical decisions.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
