"""Gemini extractor service - uses Google Gemini for document understanding."""

import os
import json
import base64
from app.config import GEMINI_API_KEY, GEMINI_MODEL, GEMINI_STRONG_MODEL

# Try to import google.generativeai
try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


def _get_client(strong: bool = False):
    """Get configured Gemini client."""
    if not GEMINI_AVAILABLE or not GEMINI_API_KEY:
        return None
    genai.configure(api_key=GEMINI_API_KEY)
    model_name = GEMINI_STRONG_MODEL if strong else GEMINI_MODEL
    return genai.GenerativeModel(model_name)


def extract_report_from_pdf(filepath: str) -> list[dict]:
    """Extract structured medical report values from a PDF (Hardcoded Mock)."""
    return [
        {"field_name": "Hemoglobin A1c", "field_value": "6.8", "unit": "%", "reference_range": "<5.7", "is_abnormal": 1},
        {"field_name": "Fasting Glucose", "field_value": "112", "unit": "mg/dL", "reference_range": "70-99", "is_abnormal": 1},
        {"field_name": "Total Cholesterol", "field_value": "210", "unit": "mg/dL", "reference_range": "<200", "is_abnormal": 1},
        {"field_name": "LDL", "field_value": "135", "unit": "mg/dL", "reference_range": "<100", "is_abnormal": 1},
        {"field_name": "HDL", "field_value": "45", "unit": "mg/dL", "reference_range": ">40", "is_abnormal": 0},
    ]

def extract_report_from_image(filepath: str) -> list[dict]:
    """Extract structured medical report values from a screenshot (Hardcoded Mock)."""
    return [
        {"field_name": "Hemoglobin A1c", "field_value": "6.8", "unit": "%", "reference_range": "<5.7", "is_abnormal": 1},
        {"field_name": "Fasting Glucose", "field_value": "112", "unit": "mg/dL", "reference_range": "70-99", "is_abnormal": 1},
        {"field_name": "Total Cholesterol", "field_value": "210", "unit": "mg/dL", "reference_range": "<200", "is_abnormal": 1},
        {"field_name": "LDL", "field_value": "135", "unit": "mg/dL", "reference_range": "<100", "is_abnormal": 1},
        {"field_name": "HDL", "field_value": "45", "unit": "mg/dL", "reference_range": ">40", "is_abnormal": 0},
    ]

def extract_medication_from_label(filepath: str) -> dict:
    """Extract medication info from a label image (Hardcoded Mock)."""
    return {"medication_name": "tamoxifen", "dosage": "20mg", "source": "mock"}

def generate_patient_summary(prediction: dict, pgx: dict, report_fields: list) -> str:
    """Generate a plain-English patient summary (Hardcoded Mock)."""
    return _mock_patient_summary(prediction, pgx, report_fields)

def generate_clinician_summary(prediction: dict, pgx: dict, report_fields: list) -> str:
    """Generate a clinician-oriented summary (Hardcoded Mock)."""
    return _mock_clinician_summary(prediction, pgx, report_fields)

def generate_doctor_note(prediction: dict, pgx: dict, report_fields: list) -> str:
    """Generate a doctor discussion note (Hardcoded Mock)."""
    return _mock_doctor_note(prediction, pgx, report_fields)



def _mock_patient_summary(prediction, pgx, report_fields):
    risk_tier = prediction.get("risk_tier", "moderate")
    risk_score = prediction.get("risk_score", 0.5)
    med = pgx.get("medication", "your medication") if pgx.get("found") else "your medication"

    return f"""Based on the analysis of your genomic data and medical reports, here is a summary of the findings:

**Disease Risk Assessment**: Your genomic profile analysis indicates a **{risk_tier} risk level** (score: {risk_score:.1%}) based on patterns identified across multiple genetic markers. This score reflects the likelihood predicted by our machine learning model trained on similar genomic datasets. It is important to understand that this is a statistical estimate and not a definitive diagnosis.

**Medication Considerations**: {'The analysis identified potential pharmacogenomic interactions with ' + med + '. ' + pgx.get("summary", "") if pgx.get("found") else "No specific pharmacogenomic interactions were flagged for the medications reviewed."}

**What This Means**: These findings are generated by an educational AI system designed to help you have more informed conversations with your healthcare provider. The results should be discussed with your doctor, who can consider your complete medical history and clinical context. We encourage you to bring this report to your next appointment and ask about the discussion questions provided."""


def _mock_clinician_summary(prediction, pgx, report_fields):
    risk_tier = prediction.get("risk_tier", "moderate")
    risk_score = prediction.get("risk_score", 0.5)
    roc = prediction.get("roc_auc", 0.0)

    return f"""**ML-Derived Risk Assessment**: XGBoost classifier indicates {risk_tier} disease risk probability ({risk_score:.1%}). Model performance: ROC-AUC {roc:.3f} on held-out test set (80/20 stratified split). Feature importance analysis identifies top contributing genomic markers aligned with known biological pathways.

**Pharmacogenomic Profile**: {'CYP enzymatic pathway analysis suggests ' + pgx.get("phenotype", "variant") + ' status for ' + pgx.get("gene", "relevant gene") + ', which may impact metabolism of ' + pgx.get("medication", "prescribed medication") + '. ' + pgx.get("evidence", "") if pgx.get("found") else "No actionable pharmacogenomic variants identified within the current rule set."}

**Clinical Correlation Required**: These results are derived from ML analysis of genomic feature matrices and should be interpreted in the context of complete clinical presentation, family history, and confirmatory diagnostic workup. The model operates on curated biomedical features and its predictions represent statistical patterns, not deterministic outcomes."""


def _mock_doctor_note(prediction, pgx, report_fields):
    risk_tier = prediction.get("risk_tier", "moderate")
    risk_score = prediction.get("risk_score", 0.5)

    abnormal = [f for f in report_fields if f.get("is_abnormal")]
    abnormal_text = ", ".join([f"{f['field_name']}: {f['field_value']} {f.get('unit', '')}" for f in abnormal]) if abnormal else "None identified"

    return f"""## Summary
Genomic risk analysis indicates **{risk_tier} risk** (probability: {risk_score:.1%}) based on XGBoost model analysis of {prediction.get('feature_importance', [{}]).__len__()} genomic markers. {'Pharmacogenomic analysis identified ' + pgx.get("caution_level", "moderate") + '-caution interaction for ' + pgx.get("medication", "medication") + '/' + pgx.get("gene", "gene") + '.' if pgx.get("found") else 'No actionable PGx findings.'}

## Key Findings
- Disease risk tier: **{risk_tier.upper()}** ({risk_score:.1%} probability)
- Model confidence: ROC-AUC {prediction.get("roc_auc", 0.0):.3f}
- Top predictive markers: {", ".join([f["feature"] for f in prediction.get("feature_importance", [])[:3]])}
- Abnormal lab values: {abnormal_text}

## Pharmacogenomic Considerations
{"- " + pgx.get("summary", "No PGx findings") if pgx.get("found") else "- No pharmacogenomic interactions identified in the current rule set"}

## Discussion Questions
1. What additional diagnostic tests would help confirm or rule out the risk indicated by the genomic analysis?
2. {"How should the " + pgx.get("phenotype", "metabolizer") + " status for " + pgx.get("gene", "gene") + " affect the current treatment plan for " + pgx.get("medication", "medication") + "?" if pgx.get("found") else "Are there medications in the current regimen that should be evaluated for pharmacogenomic interactions?"}
3. What is the recommended follow-up timeline given the identified risk level?
4. Should genetic counseling be considered based on these genomic findings?
5. How do these findings integrate with family history and other clinical data?

## Limitations
- This analysis is generated by an educational AI system and is **not a clinical diagnostic tool**
- ML predictions represent statistical patterns from training data, not deterministic outcomes
- The pharmacogenomic rules cover a limited set of medication-gene interactions
- All findings require clinical correlation and professional medical judgment
- **Always consult with a qualified healthcare provider before making medical decisions**"""
